name: bib check

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:
  push:
    branches: [main]

env:
  PYTHON_VERSION: "3.11"

jobs:
  create-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        run: pip install uv

      - name: Install requirements
        run: uv pip install --system pytest selenium

      - name: bib check
        run: pytest test_bib_check.py
